# Generated by Django 2.2.16 on 2021-10-02 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('savings', 'сберегательный'), ('payment', 'расчетный'), ('current', 'текущий')], max_length=7, verbose_name='Название')),
                ('overdraft', models.BooleanField(verbose_name='Овердрафтность')),
                ('identifier', models.CharField(default=uuid.UUID('ed0088c9-e422-4af8-ba55-73c756e7694a'), editable=False, max_length=36, verbose_name='Идентификатор')),
                ('balance', models.FloatField(default=0, verbose_name='Остаток на счете')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created'],
            },
        ),
    ]
