# Generated by Django 2.2.16 on 2021-10-02 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identifier',
            field=models.CharField(default=uuid.UUID('6493dcec-1e80-486f-b23a-2e39909e3023'), editable=False, max_length=36, unique=True, verbose_name='Идентификатор'),
        ),
    ]
